name: pinnacle_main
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.8.0
  http: ^1.2.2
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  mobx: ^2.4.0
  mobx_codegen: ^2.6.2
  sizer: ^3.0.4
  timezone: ^0.10.0
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  fonts:
    - family: Afacad
      fonts:
        - asset: assets/google_fonts/AfacadFlux-Black.ttf
          weight: 900
        - asset: assets/google_fonts/AfacadFlux-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/AfacadFlux-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/AfacadFlux-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/AfacadFlux-Light.ttf
          weight: 300
        - asset: assets/google_fonts/AfacadFlux-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/AfacadFlux-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/AfacadFlux-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/AfacadFlux-Thin.ttf
          weight: 100
  assets:
    - assets/images/profile_pic.jpg
    - assets/images/travel_image_component.jpg
    - assets/images/bike.jpg
    - assets/images/award.png
    - assets/icons/cross_icon.svg
    - assets/icons/tick_icon.svg
    